name: My actions demo

on: 
    pull_request:
        branches: [ master ]
    merge_request:
        branches: [ master ]
    push:

    
jobs:
    start_workflow:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1
            - name: capture push
              if:  github.event_name == 'push'
              run: echo "it is a push"
            - name: test
              if: github.event_name == 'merge_request'
              run: echo "it is an MR"


